--------------------------------------------------------
--  File created - Friday-October-12-2018   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Sequence CAPTURAS_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "AGUERRA"."CAPTURAS_SEQ"  MINVALUE 1 MAXVALUE 2000 INCREMENT BY 1 START WITH 1000 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence DELITOS_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "AGUERRA"."DELITOS_SEQ"  MINVALUE 1 MAXVALUE 200 INCREMENT BY 1 START WITH 100 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Table CAPTURAS
--------------------------------------------------------

  CREATE TABLE "AGUERRA"."CAPTURAS" 
   (	"ID" NUMBER(*,0), 
	"FECHA" DATE, 
	"DEPARTAMENTO" VARCHAR2(255), 
	"MUNICIPIO" VARCHAR2(255), 
	"DIA" VARCHAR2(255), 
	"BARRIO" VARCHAR2(255), 
	"ZONA" VARCHAR2(255), 
	"CLASE_SITIO" VARCHAR2(255), 
	"EDAD" NUMBER(*,0), 
	"SEXO" VARCHAR2(255), 
	"ESTADO_CIVIL" VARCHAR2(255), 
	"CLASE_EMPLEADO" VARCHAR2(255), 
	"PROFESION" NUMBER(*,0), 
	"ESCOLARIDAD" NUMBER(*,0), 
	"DELITO_ID" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MID_TERM" ;
--------------------------------------------------------
--  DDL for Table DELITOS
--------------------------------------------------------

  CREATE TABLE "AGUERRA"."DELITOS" 
   (	"ID" NUMBER(*,0), 
	"NOMBRE" VARCHAR2(255)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MID_TERM" ;
REM INSERTING into AGUERRA.CAPTURAS
SET DEFINE OFF;
Insert into AGUERRA.CAPTURAS (ID,FECHA,DEPARTAMENTO,MUNICIPIO,DIA,BARRIO,ZONA,CLASE_SITIO,EDAD,SEXO,ESTADO_CIVIL,CLASE_EMPLEADO,PROFESION,ESCOLARIDAD,DELITO_ID) values (2,to_date('01-JAN-18','DD-MON-RR'),'BOLÍVAR','ARJONA','Lunes','BARRIO SUEÑOS DE LIBERTAD','URBANA','VIAS PUBLICAS',18,'MASCULINO','SOLTERO','INDEPENDIENTE',0,0,2);
Insert into AGUERRA.CAPTURAS (ID,FECHA,DEPARTAMENTO,MUNICIPIO,DIA,BARRIO,ZONA,CLASE_SITIO,EDAD,SEXO,ESTADO_CIVIL,CLASE_EMPLEADO,PROFESION,ESCOLARIDAD,DELITO_ID) values (3,to_date('01-JAN-18','DD-MON-RR'),'BOLÍVAR','CARTAGENA (CT)','Lunes','SAN PEDRO MARTIR','URBANA','VIAS PUBLICAS',37,'MASCULINO','UNION LIBRE','EMPLEADO PARTICULAR',0,0,3);
Insert into AGUERRA.CAPTURAS (ID,FECHA,DEPARTAMENTO,MUNICIPIO,DIA,BARRIO,ZONA,CLASE_SITIO,EDAD,SEXO,ESTADO_CIVIL,CLASE_EMPLEADO,PROFESION,ESCOLARIDAD,DELITO_ID) values (4,to_date('01-JAN-18','DD-MON-RR'),'BOLÍVAR','CARTAGENA (CT)','Lunes','LA BOQUILLA','RURAL','AEROPUERTO',37,'MASCULINO','SOLTERO','EMPLEADO PARTICULAR',0,0,4);
Insert into AGUERRA.CAPTURAS (ID,FECHA,DEPARTAMENTO,MUNICIPIO,DIA,BARRIO,ZONA,CLASE_SITIO,EDAD,SEXO,ESTADO_CIVIL,CLASE_EMPLEADO,PROFESION,ESCOLARIDAD,DELITO_ID) values (5,to_date('01-JAN-18','DD-MON-RR'),'BOLÍVAR','CARTAGENA (CT)','Lunes','LA ESPERANZA','URBANA','VIAS PUBLICAS',28,'MASCULINO','UNION LIBRE','EMPLEADO PARTICULAR',0,0,2);
Insert into AGUERRA.CAPTURAS (ID,FECHA,DEPARTAMENTO,MUNICIPIO,DIA,BARRIO,ZONA,CLASE_SITIO,EDAD,SEXO,ESTADO_CIVIL,CLASE_EMPLEADO,PROFESION,ESCOLARIDAD,DELITO_ID) values (6,to_date('01-JAN-18','DD-MON-RR'),'BOLÍVAR','CARTAGENA (CT)','Lunes','CTO. BARU','URBANA','PLAYA',31,'MASCULINO','UNION LIBRE','EMPLEADO PARTICULAR',0,0,2);
Insert into AGUERRA.CAPTURAS (ID,FECHA,DEPARTAMENTO,MUNICIPIO,DIA,BARRIO,ZONA,CLASE_SITIO,EDAD,SEXO,ESTADO_CIVIL,CLASE_EMPLEADO,PROFESION,ESCOLARIDAD,DELITO_ID) values (7,to_date('01-JAN-18','DD-MON-RR'),'BOLÍVAR','MOMPÓS','Lunes','BARRIO LA TERRITORIAL','URBANA','VIAS PUBLICAS',38,'MASCULINO','CASADO','INDEPENDIENTE',0,0,2);
Insert into AGUERRA.CAPTURAS (ID,FECHA,DEPARTAMENTO,MUNICIPIO,DIA,BARRIO,ZONA,CLASE_SITIO,EDAD,SEXO,ESTADO_CIVIL,CLASE_EMPLEADO,PROFESION,ESCOLARIDAD,DELITO_ID) values (8,to_date('01-JAN-18','DD-MON-RR'),'BOLÍVAR','SAN JACINTO','Lunes','SECTOR SIETE DE AGOSTO','URBANA','VIAS PUBLICAS',25,'MASCULINO','UNION LIBRE','INDEPENDIENTE',0,0,5);
Insert into AGUERRA.CAPTURAS (ID,FECHA,DEPARTAMENTO,MUNICIPIO,DIA,BARRIO,ZONA,CLASE_SITIO,EDAD,SEXO,ESTADO_CIVIL,CLASE_EMPLEADO,PROFESION,ESCOLARIDAD,DELITO_ID) values (9,to_date('01-JAN-18','DD-MON-RR'),'BOLÍVAR','SAN JUAN NEPOMUCENO','Lunes','SECTOR COSTA DE ORO','URBANA','VIAS PUBLICAS',21,'MASCULINO','SOLTERO','INDEPENDIENTE',0,0,2);
Insert into AGUERRA.CAPTURAS (ID,FECHA,DEPARTAMENTO,MUNICIPIO,DIA,BARRIO,ZONA,CLASE_SITIO,EDAD,SEXO,ESTADO_CIVIL,CLASE_EMPLEADO,PROFESION,ESCOLARIDAD,DELITO_ID) values (10,to_date('01-JAN-18','DD-MON-RR'),'BOYACÁ','BUENAVISTA','Lunes','PARQUE PRINCIPAL','URBANA','VIAS PUBLICAS',36,'MASCULINO','SOLTERO','COMERCIANTE',0,0,6);
Insert into AGUERRA.CAPTURAS (ID,FECHA,DEPARTAMENTO,MUNICIPIO,DIA,BARRIO,ZONA,CLASE_SITIO,EDAD,SEXO,ESTADO_CIVIL,CLASE_EMPLEADO,PROFESION,ESCOLARIDAD,DELITO_ID) values (11,to_date('01-JAN-18','DD-MON-RR'),'BOYACÁ','CHIQUINQUIRÁ','Lunes','BARRIO CENTRO','URBANA','VIAS PUBLICAS',17,'MASCULINO','UNION LIBRE','EMPLEADO PARTICULAR',0,0,2);
Insert into AGUERRA.CAPTURAS (ID,FECHA,DEPARTAMENTO,MUNICIPIO,DIA,BARRIO,ZONA,CLASE_SITIO,EDAD,SEXO,ESTADO_CIVIL,CLASE_EMPLEADO,PROFESION,ESCOLARIDAD,DELITO_ID) values (12,to_date('01-JAN-18','DD-MON-RR'),'BOYACÁ','CHIQUINQUIRÁ','Lunes','BARRIO CENTRO','URBANA','VIAS PUBLICAS',19,'MASCULINO','SOLTERO','EMPLEADO PARTICULAR',0,0,2);
Insert into AGUERRA.CAPTURAS (ID,FECHA,DEPARTAMENTO,MUNICIPIO,DIA,BARRIO,ZONA,CLASE_SITIO,EDAD,SEXO,ESTADO_CIVIL,CLASE_EMPLEADO,PROFESION,ESCOLARIDAD,DELITO_ID) values (13,to_date('01-JAN-18','DD-MON-RR'),'BOYACÁ','CHIQUINQUIRÁ','Lunes','BARRIO CENTRO','URBANA','VIAS PUBLICAS',20,'MASCULINO','SOLTERO','EMPLEADO PARTICULAR',0,0,2);
Insert into AGUERRA.CAPTURAS (ID,FECHA,DEPARTAMENTO,MUNICIPIO,DIA,BARRIO,ZONA,CLASE_SITIO,EDAD,SEXO,ESTADO_CIVIL,CLASE_EMPLEADO,PROFESION,ESCOLARIDAD,DELITO_ID) values (14,to_date('01-JAN-18','DD-MON-RR'),'BOYACÁ','CHIQUINQUIRÁ','Lunes','BARRIO CENTRO','URBANA','VIAS PUBLICAS',21,'MASCULINO','SOLTERO','EMPLEADO PARTICULAR',0,0,2);
Insert into AGUERRA.CAPTURAS (ID,FECHA,DEPARTAMENTO,MUNICIPIO,DIA,BARRIO,ZONA,CLASE_SITIO,EDAD,SEXO,ESTADO_CIVIL,CLASE_EMPLEADO,PROFESION,ESCOLARIDAD,DELITO_ID) values (15,to_date('01-JAN-18','DD-MON-RR'),'BOYACÁ','CIÉNEGA','Lunes','PARQUE PRINCIPAL','URBANA','VIAS PUBLICAS',20,'MASCULINO','UNION LIBRE','ESTUDIANTE',0,0,2);
Insert into AGUERRA.CAPTURAS (ID,FECHA,DEPARTAMENTO,MUNICIPIO,DIA,BARRIO,ZONA,CLASE_SITIO,EDAD,SEXO,ESTADO_CIVIL,CLASE_EMPLEADO,PROFESION,ESCOLARIDAD,DELITO_ID) values (16,to_date('01-JAN-18','DD-MON-RR'),'BOYACÁ','DUITAMA','Lunes','SAN FERNANDO','URBANA','VIAS PUBLICAS',23,'MASCULINO','SOLTERO','INDEPENDIENTE',0,0,6);
Insert into AGUERRA.CAPTURAS (ID,FECHA,DEPARTAMENTO,MUNICIPIO,DIA,BARRIO,ZONA,CLASE_SITIO,EDAD,SEXO,ESTADO_CIVIL,CLASE_EMPLEADO,PROFESION,ESCOLARIDAD,DELITO_ID) values (17,to_date('01-JAN-18','DD-MON-RR'),'BOYACÁ','DUITAMA','Lunes','BARRIO CENTRO','URBANA','VIAS PUBLICAS',33,'MASCULINO','UNION LIBRE','EMPLEADO PARTICULAR',0,0,2);
Insert into AGUERRA.CAPTURAS (ID,FECHA,DEPARTAMENTO,MUNICIPIO,DIA,BARRIO,ZONA,CLASE_SITIO,EDAD,SEXO,ESTADO_CIVIL,CLASE_EMPLEADO,PROFESION,ESCOLARIDAD,DELITO_ID) values (18,to_date('01-JAN-18','DD-MON-RR'),'BOYACÁ','GACHANTIVÁ','Lunes','PARQUE PRINCIPAL','URBANA','VIAS PUBLICAS',22,'MASCULINO','SOLTERO','INDEPENDIENTE',0,0,2);
Insert into AGUERRA.CAPTURAS (ID,FECHA,DEPARTAMENTO,MUNICIPIO,DIA,BARRIO,ZONA,CLASE_SITIO,EDAD,SEXO,ESTADO_CIVIL,CLASE_EMPLEADO,PROFESION,ESCOLARIDAD,DELITO_ID) values (19,to_date('01-JAN-18','DD-MON-RR'),'BOYACÁ','SOATÁ','Lunes','EL CENTRO','URBANA','VIAS PUBLICAS',19,'MASCULINO','SOLTERO','EMPLEADO PARTICULAR',0,0,2);
Insert into AGUERRA.CAPTURAS (ID,FECHA,DEPARTAMENTO,MUNICIPIO,DIA,BARRIO,ZONA,CLASE_SITIO,EDAD,SEXO,ESTADO_CIVIL,CLASE_EMPLEADO,PROFESION,ESCOLARIDAD,DELITO_ID) values (20,to_date('01-JAN-18','DD-MON-RR'),'BOYACÁ','TUNJA (CT)','Lunes','VDA.TRAS DEL ALTO','RURAL','TRAMO DE VIA',37,'MASCULINO','UNION LIBRE','AGRICULTOR',0,0,7);
Insert into AGUERRA.CAPTURAS (ID,FECHA,DEPARTAMENTO,MUNICIPIO,DIA,BARRIO,ZONA,CLASE_SITIO,EDAD,SEXO,ESTADO_CIVIL,CLASE_EMPLEADO,PROFESION,ESCOLARIDAD,DELITO_ID) values (21,to_date('01-JAN-18','DD-MON-RR'),'CALDAS','ANSERMA','Lunes','AVENIDA LIBERTADOR','URBANA','VIAS PUBLICAS',32,'MASCULINO','SOLTERO','INDEPENDIENTE',0,0,2);
Insert into AGUERRA.CAPTURAS (ID,FECHA,DEPARTAMENTO,MUNICIPIO,DIA,BARRIO,ZONA,CLASE_SITIO,EDAD,SEXO,ESTADO_CIVIL,CLASE_EMPLEADO,PROFESION,ESCOLARIDAD,DELITO_ID) values (22,to_date('01-JAN-18','DD-MON-RR'),'CALDAS','CHINCHINÁ','Lunes','LA NUBIA','URBANA','VIAS PUBLICAS',52,'MASCULINO','UNION LIBRE','INDEPENDIENTE',0,0,8);
Insert into AGUERRA.CAPTURAS (ID,FECHA,DEPARTAMENTO,MUNICIPIO,DIA,BARRIO,ZONA,CLASE_SITIO,EDAD,SEXO,ESTADO_CIVIL,CLASE_EMPLEADO,PROFESION,ESCOLARIDAD,DELITO_ID) values (23,to_date('01-JAN-18','DD-MON-RR'),'CALDAS','CHINCHINÁ','Lunes','PANORAMA','URBANA','VIAS PUBLICAS',39,'MASCULINO','SOLTERO','DESEMPLEADO',0,0,2);
Insert into AGUERRA.CAPTURAS (ID,FECHA,DEPARTAMENTO,MUNICIPIO,DIA,BARRIO,ZONA,CLASE_SITIO,EDAD,SEXO,ESTADO_CIVIL,CLASE_EMPLEADO,PROFESION,ESCOLARIDAD,DELITO_ID) values (24,to_date('01-JAN-18','DD-MON-RR'),'CALDAS','MANIZALES (CT)','Lunes','BARRIO CHIPRE','URBANA','CASAS DE HABITACION',58,'MASCULINO','CASADO','COMERCIANTE',0,0,4);
Insert into AGUERRA.CAPTURAS (ID,FECHA,DEPARTAMENTO,MUNICIPIO,DIA,BARRIO,ZONA,CLASE_SITIO,EDAD,SEXO,ESTADO_CIVIL,CLASE_EMPLEADO,PROFESION,ESCOLARIDAD,DELITO_ID) values (25,to_date('01-JAN-18','DD-MON-RR'),'CALDAS','MANIZALES (CT)','Lunes','KENNEDY','URBANA','VIAS PUBLICAS',25,'FEMENINO','SOLTERO','INDEPENDIENTE',0,0,9);
Insert into AGUERRA.CAPTURAS (ID,FECHA,DEPARTAMENTO,MUNICIPIO,DIA,BARRIO,ZONA,CLASE_SITIO,EDAD,SEXO,ESTADO_CIVIL,CLASE_EMPLEADO,PROFESION,ESCOLARIDAD,DELITO_ID) values (26,to_date('01-JAN-18','DD-MON-RR'),'CALDAS','MANIZALES (CT)','Lunes','SOLFERINO','URBANA','VIAS PUBLICAS',22,'MASCULINO','SOLTERO','DESEMPLEADO',0,0,10);
Insert into AGUERRA.CAPTURAS (ID,FECHA,DEPARTAMENTO,MUNICIPIO,DIA,BARRIO,ZONA,CLASE_SITIO,EDAD,SEXO,ESTADO_CIVIL,CLASE_EMPLEADO,PROFESION,ESCOLARIDAD,DELITO_ID) values (27,to_date('01-JAN-18','DD-MON-RR'),'CALDAS','MANIZALES (CT)','Lunes','CENTRO','URBANA','VIAS PUBLICAS',44,'MASCULINO','UNION LIBRE','INDEPENDIENTE',0,0,9);
Insert into AGUERRA.CAPTURAS (ID,FECHA,DEPARTAMENTO,MUNICIPIO,DIA,BARRIO,ZONA,CLASE_SITIO,EDAD,SEXO,ESTADO_CIVIL,CLASE_EMPLEADO,PROFESION,ESCOLARIDAD,DELITO_ID) values (28,to_date('01-JAN-18','DD-MON-RR'),'CALDAS','MANIZALES (CT)','Lunes','PUERTA DEL SOL','URBANA','VIAS PUBLICAS',22,'MASCULINO','SOLTERO','INDEPENDIENTE',0,0,9);
Insert into AGUERRA.CAPTURAS (ID,FECHA,DEPARTAMENTO,MUNICIPIO,DIA,BARRIO,ZONA,CLASE_SITIO,EDAD,SEXO,ESTADO_CIVIL,CLASE_EMPLEADO,PROFESION,ESCOLARIDAD,DELITO_ID) values (29,to_date('01-JAN-18','DD-MON-RR'),'CALDAS','MANZANARES','Lunes','CENTRO','URBANA','VIAS PUBLICAS',59,'MASCULINO','SOLTERO','INDEPENDIENTE',0,0,2);
Insert into AGUERRA.CAPTURAS (ID,FECHA,DEPARTAMENTO,MUNICIPIO,DIA,BARRIO,ZONA,CLASE_SITIO,EDAD,SEXO,ESTADO_CIVIL,CLASE_EMPLEADO,PROFESION,ESCOLARIDAD,DELITO_ID) values (30,to_date('01-JAN-18','DD-MON-RR'),'CALDAS','MANZANARES','Lunes','CENTRO','URBANA','VIAS PUBLICAS',20,'MASCULINO','SOLTERO','INDEPENDIENTE',0,0,9);
Insert into AGUERRA.CAPTURAS (ID,FECHA,DEPARTAMENTO,MUNICIPIO,DIA,BARRIO,ZONA,CLASE_SITIO,EDAD,SEXO,ESTADO_CIVIL,CLASE_EMPLEADO,PROFESION,ESCOLARIDAD,DELITO_ID) values (31,to_date('01-JAN-18','DD-MON-RR'),'CALDAS','MANZANARES','Lunes','LOMBO','URBANA','VIAS PUBLICAS',26,'MASCULINO','UNION LIBRE','INDEPENDIENTE',0,0,5);
Insert into AGUERRA.CAPTURAS (ID,FECHA,DEPARTAMENTO,MUNICIPIO,DIA,BARRIO,ZONA,CLASE_SITIO,EDAD,SEXO,ESTADO_CIVIL,CLASE_EMPLEADO,PROFESION,ESCOLARIDAD,DELITO_ID) values (32,to_date('01-JAN-18','DD-MON-RR'),'CALDAS','MANZANARES','Lunes','CENTRO','URBANA','VIAS PUBLICAS',46,'MASCULINO','UNION LIBRE','INDEPENDIENTE',0,0,2);
REM INSERTING into AGUERRA.DELITOS
SET DEFINE OFF;
Insert into AGUERRA.DELITOS (ID,NOMBRE) values (1,'ARTÍCULO 109. HOMICIDIO CULPOSO ( EN ACCIDENTE DE TRÁNSITO)');
Insert into AGUERRA.DELITOS (ID,NOMBRE) values (2,'ARTÍCULO 111. LESIONES PERSONALES');
Insert into AGUERRA.DELITOS (ID,NOMBRE) values (3,'ARTÍCULO 229. VIOLENCIA INTRAFAMILIAR');
Insert into AGUERRA.DELITOS (ID,NOMBRE) values (4,'ARTÍCULO 376. TRÁFICO -  FABRICACIÓN O PORTE DE ESTUPEFACIENTES');
Insert into AGUERRA.DELITOS (ID,NOMBRE) values (5,'ARTÍCULO 429. VIOLENCIA CONTRA SERVIDOR PÚBLICO');
Insert into AGUERRA.DELITOS (ID,NOMBRE) values (6,'ARTÍCULO 447. RECEPTACIÓN');
Insert into AGUERRA.DELITOS (ID,NOMBRE) values (7,'ARTÍCULO 120. LESIONES CULPOSAS ( EN ACCIDENTE DE TRANSITO )');
Insert into AGUERRA.DELITOS (ID,NOMBRE) values (8,'ARTÍCULO 365. FABRICACIÓN -  TRÁFICO -  PORTE O TENENCIA DE ARMAS DE FUEGO - ACCESORIOS -  PARTES O MUNICIONES');
Insert into AGUERRA.DELITOS (ID,NOMBRE) values (9,'ARTÍCULO 265. DAÑO EN BIEN AJENO');
Insert into AGUERRA.DELITOS (ID,NOMBRE) values (10,'ARTÍCULO 448. FUGA DE PRESOS');
--------------------------------------------------------
--  DDL for Index SYS_C007868
--------------------------------------------------------

  CREATE UNIQUE INDEX "AGUERRA"."SYS_C007868" ON "AGUERRA"."DELITOS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MID_TERM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007869
--------------------------------------------------------

  CREATE UNIQUE INDEX "AGUERRA"."SYS_C007869" ON "AGUERRA"."CAPTURAS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MID_TERM" ;
--------------------------------------------------------
--  Constraints for Table CAPTURAS
--------------------------------------------------------

  ALTER TABLE "AGUERRA"."CAPTURAS" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MID_TERM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table DELITOS
--------------------------------------------------------

  ALTER TABLE "AGUERRA"."DELITOS" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MID_TERM"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CAPTURAS
--------------------------------------------------------

  ALTER TABLE "AGUERRA"."CAPTURAS" ADD CONSTRAINT "DELITO_FK" FOREIGN KEY ("DELITO_ID")
	  REFERENCES "AGUERRA"."DELITOS" ("ID") ENABLE;
